sudo: false

language: node_js

node_js:
  - "10"
  - "12"

# keep the npm cache to speed up installs
cache:
  directories:
    - "$HOME/.npm"

branches:
  only:
    - master

install:
  - npm ci

script:
  - npm run test

after_success:
  - npm run cov:send
  - npm run cov:check

deploy:
  provider: npm
  email: rproenza86@gmail.com
  api_key:
    secure: sPqDnrdJEEKZxZqWGApTYz3B6aprvq2Zamu7hZhz6ljzfyMP2syrLqZtsz62g92fdtylyhuqjBVdqOBUAEMZNL7V1FouWoT8iObzNkWmzuJ+1UVIhuFynfhhG6bbvT7isDGypvJjDscz9BUXzBC92W2BfXFOuU/ZYHCa+NXPWnMEvA5k75gyFNl63ee3U3XPkE0xl88XGYWFkkkcunlCCbMFecFsZS/h6SDviDus9Pz7xyjzWlECakp31qlPXKLPH5b5KuXRbCM7KRZbJx9nSmSlupbArRAZ24N57yqZdtOSUuipULdFbBfaYzLIvurmphHU8A+LDn60g0UhjOzLAN4XOgZ4VssXQAePHfNNT29Pzb1IuPyVisjjhaPvhA2UIA/Dk2TY04MB0Wzo04xl8I5xdobdwN5rEE5ycZa8Yrkeigfs6zfZRAQRr6VIkT6fQTgzDk/5nvjP/zd4DSIjBw5zZUHe6dsY1M6EH+OrHZqfRCLtwJmwSa9ayifUjoNIuz1iVyWvG8GJMNJrQ0hOhRNeAXFop01C9XXNsPpezMsUWZ2DT2j5ZYzDnlx2bEMhVK6LGcZx8U4KdbE+1D5mewXVVfoLMPKr95RHMp5K533emMULedQGrKVhQlLwMKfOrC5UoykfhQlrVayIyue/xu6F/n/B/kgEwa5cSJq2p1g=
  on:
    branch: master

COVERALLS_REPO_TOKEN:
  secure: B3yn2hfI9HmHHlZ0pshTFKcBLJgzqhogDibFltOnDnICYli5DkPVal2wn+Dp5N67Qnk+u+lf7JOIZYoa0AjWAq+4u4K1vuv/ne0RXZXpnF1WG13QRHnea1BLS3xR3pAe/yH2I2eAQxAjF0zMfE34psbO87nmzICxvZFG1r8e9ltbmBI4spC1TmQkCa0aJyZBNdObXYSi1AMv1ZJhbrVFqh5KKTk+VPfqSIGGvp/hi5tuGleOHJddENqS4nG56pBAQvzLagzzc/K/AUTKYYzmPCcT59wGeOCFjeWUVfc0UhgulMN+zriDoS6z0L/rMi6VpRMXwLgf0paWXb3JvdpvR3p2D1B8utINlmMAn4dVm6lUuhOckF4IHMm37m3CQ5lxcLIi+1rB9ftJjL89eW7C3YejYTX0izTOV0CHHw234jxsSFxidINaBdTDB0993FUUT3uwiZzcKSIP/X+On07h8z4nWcUMA7QXxJJFV069iNrb+vexNC/+4L9kPcx0B67aS/iO/IjJ7oGU29hMl9vl3tFC2/CF4uAHykI2iPzuhqPBAEhwMRuJ4W/q9t6k+RNYx18O6fi2vXl2OOw6kg3TQ2IemIcNuXbL9FQPd1at9Z+/Ch4Fay/d26U03qw8WrxOYgIuXIbPgebeSSgz2X8aHJIxg2CMrCFMnpYfF42wvlw=
